"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
import time


# driver function for our program
def main():
    """
    Forms separate lists of the triangular numbers, pentagonal numbers,
    and hexagonal numbers.  Then the list of triangular numbers is
    converted to a set to then compute the intersection of the set with
    the other two lists.  The third argument in that list is then returned.
    """
    start_time = time.time()

    triangular_nums = []
    pentagonal_nums = []
    hexagonal_nums = []

    for i in range(1, 500000):
        triangular_nums.append(i * (i + 1) * (1 / 2))

    for i in range(1, 500000):
        pentagonal_nums.append(i * (3*i - 1) * (1 / 2))

    for i in range(1, 500000):
        hexagonal_nums.append(i * (2*i - 1))

    triangular_nums = set(triangular_nums)

    # calculate end time and print results
    intersection = list(triangular_nums.intersection(pentagonal_nums, hexagonal_nums))
    end_time = time.time() - start_time
    print("Found %s in %2f seconds." % (intersection[2], end_time))


# While not required, it is considered good practice to have
# a main function and use this syntax to call it.
if __name__ == "__main__":
    main()
